### ISSUE TITLE
SpatioTemporalConstraints meaning and behaviour

### ISSUE THREAD

**Issue by ogencoglu** [insight-platform/medium-similari-rapid-oriented-sort#1]
Nice article Oleg! 

Can you elaborate on what exactly `SpatioTemporalConstraints` is and what does it mean to have the values `(1, 1.0) `in your `__init__.py` ?

```
    constraints = SpatioTemporalConstraints()
    constraints.add_constraints([(1, 1.0)])
```

**Comment by bwsw** [comment]
@ogencoglu hello, well, the constraint helps to increase the performance when the scene involves a lot of objects; otherwise, it can be omitted. Speaking on your code above, `(1, 1.0) means that if the epoch difference between a track and an observation is 1 (next epoch), the distance between object centers must be less than the sum of their radiuses (circumscribing circle radius). 

You may also specify, e.g. `[(1, 1.0), (2, 1.5), (10, 5.0)]` to configure the expectations of how far objects may dispense.

**Comment by ogencoglu** [comment]
Thanks for the explanation.
